version: '3.8'

services:
  # Base de Datos PostgreSQL
  postgres-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Defina POSTGRES_PASSWORD en el archivo .env}
      POSTGRES_DB: ${POSTGRES_DB:-lacatracha}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Sistema La Catracha (Frontend + Backend unificados)
  la-catracha-app:
    build: .
    restart: always
    environment:
      # URL Interna para Docker (el nombre del servicio 'postgres-db')
      POSTGRES_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:?Defina POSTGRES_PASSWORD en el archivo .env}@postgres-db:5432/${POSTGRES_DB:-lacatracha}
      PORT: 3000
      PUBLIC_PATH: public
      JWT_SEED: ${JWT_SEED:?Defina JWT_SEED en el archivo .env}
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - postgres-db

volumes:
  postgres-data:
